name: simula-openvr
version: 0.0.0
synopsis: Haskell bindings for OpenVR.
author:
    - George Singer
    - Zac Slade

default-extensions:
  - GADTs
  - ConstraintKinds
  - KindSignatures
  - StandaloneDeriving
  - FlexibleInstances
  - FlexibleContexts
  - MultiParamTypeClasses
  - FunctionalDependencies
  - ScopedTypeVariables
  - RankNTypes
  - RecursiveDo
  - DefaultSignatures
  - PatternSynonyms
  - LambdaCase
  - ForeignFunctionInterface
  - QuasiQuotes
  - TemplateHaskell
  - OverloadedStrings
  - TypeInType
  - TypeFamilies
  - AllowAmbiguousTypes
  - RecordWildCards

dependencies:
  - base >= 4.9 && < 5
  - containers
  - linear
  - unix
  - lens

build-tools:
  - c2hs

extra-libraries:
  - openvr_api
  - stdc++

include-dirs:
  - openvr/headers
  - cbits

ghc-options: -pgmlg++

library:
  source-dirs: src
  c-sources: cbits/*.cpp
  exposed-modules: OpenVR
